# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - joint_state_controller_arma_controller

  joint_state_controller_arma_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - base_revolve
      - link1_revolve
      - link2_revolve
      - link3_revolve
      - link4_revolve
    action_ns: follow_joint_trajectory
    default: true