# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_controller_arma_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_state_controller_arma_controller:
  ros__parameters:
    joints:
      - base_revolve
      - link1_revolve
      - link2_revolve
      - link3_revolve
      - link4_revolve
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity