# Default initial positions for cobot_trial2's ros2_control fake system
initial_positions:
  link1_revolve: -0.785
  link2_revolve: 0.2
  base_revolve: 0.3
  link3_revolve: -2.356
  link4_revolve: 0.1
